name: Actions

on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: | #csv or \n for arrays
            jshernandez05
            marstwo2
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{steps.hello.outputs.time }}"
          echo $HELLO
